config/routes.rb
Rails.application.routes.draw do
  root 'tags#index'
  require 'resque/server'
  mount Resque::Server.new, at: '/queue'

  get '/login' => 'sessions#new', as: :new_session
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  resources :registrations, only: [:new, :create]
  get '/register' => 'registrations#new'

  get '/install' => 'installation#install', as: :install

  resources :tags do
    resources :tag_versions, only: [:index, :show] do
      member do
        get :diff
      end
    end
  end
end

app/models/tag_version.rb
class TagVersion < ApplicationRecord
  belongs_to :tag

  def host_url_pathname
    URI.parse(tag.full_url).path
  end

  def is_currently_live?
    tag.currently_live_tag_version_id == id
  end

  def sha
    hashed_content.slice(0, 8)
  end

  def original_content
    @original_content ||= original_content_host_url ? HTTParty.get(original_content_host_url).to_s : nil
  end

  def minified_content
    @minified_content ||= minified_content_host_url ? HTTParty.get(minified_content_host_url).to_s : nil
  end

  def formatted_content
    @formatted_content ||= formatted_content_host_url ? HTTParty.get(formatted_content_host_url).to_s : nil
  end

  def sha
    hashed_content.slice(0, 8)
  end

  def previous_version
    tag.tag_versions.older_than(created_at).most_recent_first.limit(1).first
  end

  def first_version?
    previous_version.nil?
  end
end

app/controllers/tag_versions_controller.rb
class TagVersionsController < LoggedInController
  protect_from_forgery except: :content
  before_action :find_tag_and_tag_version

  def show
    @breadcrumbs = [ 
      { text: 'Tags', url: tags_path }, 
      { text: @tag.hostname_and_path, url: tag_path(@tag) },
      { text: "#{@tag_version.created_at.formatted_short} release" }
    ]
  end

  def diff
    previous_tag_version = @tag_version.previous_version
    formatted_content = TagManager::JsBeautifier.beautify_string!(@tag_version.original_content)
    previous_version_formatted_content = previous_tag_version ? TagManager::JsBeautifier.beautify_string!(previous_tag_version.original_content) : nil
    diff_analyzer = DiffAnalyzer.new(
      new_content: formatted_content,
      previous_content: previous_version_formatted_content,
      num_lines_of_context: 7,
      include_diff_info: true
    )
    render turbo_stream: turbo_stream.replace(
      "tag_version_#{@tag_version.id}_diff",
      partial: 'tag_versions/diff',
      locals: { 
        tag: @tag, 
        tag_version: @tag_version, 
        additions_html: diff_analyzer.html_split_diff_additions&.html_safe, 
        deletions_html: diff_analyzer.html_split_diff_deletions&.html_safe,
        num_additions: diff_analyzer.num_additions,
        num_deletions: diff_analyzer.num_deletions,
        total_changes: diff_analyzer.total_changes
      }
    )
  end

  private

  def find_tag_and_tag_version
    @tag = current_organization.tags.find(params[:tag_id])
    @tag_version = @tag.tag_versions.find(params[:id])
  end
end

app/views/tag_versions/_diff.html.erb
<%= turbo_frame_tag "tag_version_#{tag_version.id}_diff" do %>
  <style id='diffy-css'><%= Diffy::CSS %></style>
  <style>
    .diff-content .diff {
      overflow: inherit;
    }
    .diff-content ul {
      background: rgb(243 244 246);
    }
    .diff-content li {
      list-style-type: decimal;
      list-style-position: outside;
      margin-left: 35px;
      height: auto;
      word-break: break-word;
    }
    .diff-content li:not(.diff-block-info) {
      display: list-item;
    }
    .diff-content li.diff-block-info {
      padding: 5px;
    }
    .diff-content li.diff-block-info span {
      margin-left: 35px;
    }
    .diff-content li::marker {
      color: #24292f;
    }
    .diff-content li.symbol {
      color: #24292f;
    }
    .diff-content li.diff-block-info {
      background: #eff6ff;
    }
    .diff-content li.unchanged {
      background: white;
    }
    .diff-content li.unchanged:hover {
      background: white;
    }
    .diff-content li.ins {
      background: #dfd;
    }
    .diff-content li.ins:hover {
      background: #dfd;
    }
    .diff-content li.del {
      background: #fee;
    }
    .diff-content li.del:hover {
      background: #fee;
    }
    .diff-content li.diff-comment {
      display: none;
    }
    .diff ins strong {
      background: #abf2bc
    }
  </style>

  <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 mt-8 mb-8">
    <div class='grid grid-cols-3 text-md border border-gray-400 rounded-t-md p-3 flex items-center bg-gray-100'>
      <div class='col-span-2'>
        <span>Released <span class='font-semibold italic'><%= time_ago_in_words(tag_version.created_at) %> ago</span>.</span>
      </div>
      <div class='col-span-1 text-end'>
        <% if tag_version.is_currently_live? %>
          <div class='h-2 w-2 rounded-full bg-green-400 inline-block mr-1'></div> Live version
        <% else %>
          <%= form_with model: tag do |f| %>
            <%= f.hidden_field :currently_live_tag_version_id, value: tag_version.id %>
            <button type='submit' class='border-2 rounded-md border-gray-300 text-blue-600 py-2 px-4 bg-gray-100 hover:bg-gray-200'>
              Set as live version
            </button>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class='grid grid-cols-3 text-md border border-gray-400 rounded-b-md mb-5 p-3 flex items-center mb-5'>
      <div class='col-span-2'>
        <span class='text-md truncate block italic'><%= tag_version.minified_content_host_url || tag_version.original_content_host_url %></span>
      </div>
      <div class='col-span-1 text-end'>
        Commit <span class='italic'><%= tag_version.sha %></span>
      </div>
    </div>

    <div class='border-t border-l border-r border-gray-400 bg-gray-100 rounded-t-md p-3'>
      <span class='text-green-600'>
        +<%= num_additions %>
      </span> 
      <span class='text-red-600 mr-1'>
        -<%= num_deletions %>
      </span>

      <% num_addition_squares = total_changes <= 5 ? num_additions : ((num_additions.to_f / (total_changes.to_f))*5.0).to_i %>
      <% num_deletion_squares = total_changes <= 5 ? num_deletions : ((num_deletions.to_f / (total_changes.to_f))*5.0).to_i %>
      <% num_neutral_squares = 5 - num_addition_squares - num_deletion_squares %>
      <% num_addition_squares.times do %>
        <div class='h-3 w-3 bg-green-600 border border-gray-400 inline-block' style='margin-left: -3px'></div>
      <% end %>
      <% num_deletion_squares.times do %>
        <div class='h-3 w-3 bg-red-600 border border-gray-400 inline-block' style='margin-left: -3px'></div>
      <% end %>
      <% num_neutral_squares.times do %>
        <div class='h-3 w-3 bg-gray-300 border border-gray-400 inline-block' style='margin-left: -3px'></div>
      <% end %>

      <span class='ml-2'><%= tag.full_url %></span>
    </div>

    <div class='grid grid-cols-2 diff-content border border-gray-400 rounded-b-md overflow-hidden'>
      <div>
        <%= deletions_html %>
      </div>
      <div>
        <%= additions_html %>
      </div>
    </div>
  </div>
<% end %>

app/views/tag_versions/show.html.erb
<%= turbo_frame_tag "tag_version_#{@tag_version.id}_diff", src: diff_tag_tag_version_path(@tag, @tag_version) do %>
  <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 mt-8 mb-8">
  <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 mt-8 mb-8">
    
    <div class='grid grid-cols-3 text-md border border-gray-400 rounded-t-md p-3 flex items-center bg-gray-100'>
      <div class='col-span-2'>
        <span>Released <span class='font-semibold italic'><%= time_ago_in_words(@tag_version.created_at) %> ago</span>.</span>
      </div>
      <div class='col-span-1 text-end'>
      </div>
    </div>
    <div class='grid grid-cols-3 text-md border border-gray-400 rounded-b-md mb-5 p-3 flex items-center mb-5'>
      <div class='col-span-2'>
        <span class='text-md truncate block italic'><%= @tag_version.minified_content_host_url || @tag_version.original_content_host_url %></span>
      </div>
      <div class='col-span-1 text-end'>
        Commit <span class='italic'><%= @tag_version.sha %></span>
      </div>
    </div>

    <div class='border-t border-l border-r border-gray-400 bg-gray-100 rounded-t-md p-3 animate-pulse'>
      <% 5.times do %>
        <div class='h-3 w-3 bg-gray-300 border-gray-400 inline-block -ml-1'></div>
      <% end %>
      <span class='ml-2'><%= @tag.full_url %></span>
    </div>

    <div class='grid grid-cols-2 diff-content border border-gray-400 rounded-b-md overflow-hidden p-4 animate-pulse'>
      <div>
        <div class='h-4 w-[75%] bg-gray-300 border-gray-400 m-1 rounded'></div>
        <div class='h-4 w-[50%] bg-gray-300 border-gray-400 m-1 rounded'></div>
        <div class='h-4 w-[60%] bg-gray-300 border-gray-400 m-1 rounded'></div>
        <div class='h-4 w-[30%] bg-gray-300 border-gray-400 m-1 rounded'></div>
        <div class='h-4 w-[40%] bg-gray-300 border-gray-400 m-1 rounded'></div>
        <div class='h-4 w-[90%] bg-gray-300 border-gray-400 m-1 rounded'></div>
      </div>
      <div>
        <div class='h-4 w-[40%] bg-gray-300 border-gray-400 m-1 rounded'></div>
        <div class='h-4 w-[20%] bg-gray-300 border-gray-400 m-1 rounded'></div>
        <div class='h-4 w-[80%] bg-gray-300 border-gray-400 m-1 rounded'></div>
        <div class='h-4 w-[60%] bg-gray-300 border-gray-400 m-1 rounded'></div>
        <div class='h-4 w-[30%] bg-gray-300 border-gray-400 m-1 rounded'></div>
      </div>
    </div>
  </div>
<% end %>