config/routes.rb
Rails.application.routes.draw do
  root 'tags#index'
  require 'resque/server'
  mount Resque::Server.new, at: '/queue'

  get '/login' => 'sessions#new', as: :new_session
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  resources :registrations, only: [:new, :create]
  get '/register' => 'registrations#new'

  get '/install' => 'installation#install', as: :install

  resources :tags do
    resources :tag_versions, only: [:index, :show] do
      member do
        get :diff
      end
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :organization
  belongs_to :tag_identifying_data, optional: true
  belongs_to :currently_live_tag_version, class_name: TagVersion.to_s, optional: true
  has_many :tag_versions, dependent: :destroy
  has_many :release_checks, dependent: :destroy

  before_create :set_parsed_url_attributes
  after_create :find_and_apply_tag_identifying_data
  # after_create_commit { NewTagJob.perform_later(self) }
  after_create_commit { ReleaseDetector.new(self).capture_new_tag_version_if_necessary }
  after_update :check_for_new_currently_live_tag_version

  def set_parsed_url_attributes
    parsed_url = URI.parse(self.full_url)
    self.url_host = parsed_url.host
    self.url_path = parsed_url.path
    self.url_query = parsed_url.query

    parsed_url.scheme = 'https' if parsed_url.scheme.nil?
    self.full_url = parsed_url.to_s
  rescue => e
    errors.add(:base, "Invalid URL: #{e.message}")
  end

  def friendly_name
    has_tag_identifying_data? ? tag_identifying_data.name : nil
  end

  def hostname_and_path
    url_host + url_path
  end

  def most_recent_tag_version
    tag_versions.most_recent_first.limit(1).first
  end

  def most_recent_release_check
    release_checks.most_recent_first.limit(1).first
  end

  def find_and_apply_tag_identifying_data(force_update = false)
    if full_url.present? && (!has_tag_identifying_data? || force_update)
      update!(tag_identifying_data: TagIdentifyingData.for_tag(self))
    end
  end

  def has_tag_identifying_data?
    tag_identifying_data_id.present?
  end

  def has_image?
    has_tag_identifying_data? && tag_identifying_data.image.attached?
  end

  def image_url
    has_image? ? tag_identifying_data.image.service_url : nil
  end

  private

  def check_for_new_currently_live_tag_version
    organization.publish_configuration_json if !saved_changes['currently_live_tag_version_id'].nil?
  end
end

app/controllers/tags_controller.rb
class TagsController < LoggedInController
  def index
    @tags = current_organization.tags
    @breadcrumbs = [{ text: 'Tags' }]
  end

  def show
    @tag = current_organization.tags.find(params[:id])
    @breadcrumbs = [{ text: 'Tags', url: tags_path }, { text: @tag.hostname_and_path }]
  end

  def new
    @breadcrumbs = [{ text: 'Tags', url: tags_path }, { text: 'Host new tag' }]
  end

  def update
    @tag = current_organization.tags.find(params[:id])
    if @tag.update(update_tag_params)
      flash[:banner] = { type: 'success', message: "Updated live tag version to #{@tag.currently_live_tag_version.sha}." }
      redirect_to tag_path(@tag)
    else
      flash[:banner] = { type: 'error', message: @tag.errors.full_messages.join(', ') }
      redirect_to tag_path(@tag)
    end
  end

  def create
    @tag = current_organization.tags.new(tag_params)
    if @tag.save
      redirect_to tag_path(@tag)
    else
      render turbo_stream: turbo_stream.replace(
        "new_tag",
        partial: 'tags/form',
        locals: {
          tag: @tag,
          error_message: @tag.errors.full_messages.join(', '),
        }
      )
    end
  end

  def destroy
    @tag = current_organization.tags.find(params[:id])
    @tag.destroy
    flash[:banner] = { type: 'success', message: "You are no longer hosting #{@tag.hostname_and_path}" }
    redirect_to root_path
  end

  private

  def tag_params
    params.require(:tag).permit(:full_url)
  end

  def update_tag_params
    params.require(:tag).permit(:currently_live_tag_version_id)
  end
end

app/views/tags/_edit.html.erb
<%= render_as_modal title: "Edit #{tag.try_friendly_name}", sub_title: tag.full_url do %>
  <div class='tagsafe-modal-body'>
    <%= render 'form', container: container, tag_snippet: tag_snippet, tag: tag %>
  </div>
<% end %>

app/views/tags/_form.html.erb
<%= form_with model: tag, data: { controller: 'loading_form' } do |f| %>
  <div class="grid max-w-3xl grid-cols-1 gap-6 lg:max-w-7xl lg:grid-flow-col-dense lg:grid-cols-4">
    <div class="space-y-6 lg:col-start-1 lg:col-span-4 border rounded-md overflow-hidden p-6">
      <% if local_assigns[:error_messages] && error_messages.any? %>
        <div class="rounded-md bg-red-50 p-4">
          <div class="flex">
            <div class="flex-shrink-0">
              <!-- Heroicon name: mini/x-circle -->
              <svg class="h-5 w-5 text-red-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.28 7.22a.75.75 0 00-1.06 1.06L8.94 10l-1.72 1.72a.75.75 0 101.06 1.06L10 11.06l1.72 1.72a.75.75 0 101.06-1.06L11.06 10l1.72-1.72a.75.75 0 00-1.06-1.06L10 8.94 8.28 7.22z" clip-rule="evenodd" />
              </svg>
            </div>
            <div class="ml-3">
              <h3 class="text-sm font-medium text-red-800">There were errors with your submission</h3>
              <div class="mt-2 text-sm text-red-700">
                <span>
                  <%= error_messages.join(' ') %>
                </span>
              </div>
            </div>
          </div>
        </div>
      <% end %>

      <div class='form-floating'>
        <label for="" class="block text-sm font-medium text-gray-700">Tag URL</label>
        <%= f.text_field :full_url, 
                          value: tag.full_url, 
                          placeholder:'e.g. "https://cdn.swishjam.com/latest/src.js"', 
                          type:'text',
                          class: 'block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm' %>
      </div>
      <div class="grid justify-items-end">
        <button type='submit' class='inline-flex items-center justify-center rounded-md border border-transparent bg-blue-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:ring-offset-gray-100'>
          Host tag
        </button>
      </div>
    </div>
  </div>
<% end %>

app/views/tags/index.html.erb
<%= render 'partials/page_header', page_title: 'Hosted Tags' %>

<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 mt-8">
  <% if @tags.any? %>
    <div class="overflow-hidden bg-white shadow sm:rounded-md">
      <ul role="list" class="divide-y divide-gray-200">
        <% @tags.each do |tag| %>
          <li>
            <%= link_to tag_path(tag), class: 'block hover:bg-gray-50' do %>
              <div class="flex items-center px-4 py-4 sm:px-6">
                <div class="flex min-w-0 flex-1 items-center">
                  <div class="flex-shrink-0">
                    <% if tag.has_image? %>
                      <%= image_tag tag.image_url, class: 'h-12 w-12 rounded-full border border-gray-200' %>
                    <% else %>
                      <div class='h-12 w-12 rounded-full bg-gray-100 p-2'>
                        <svg class="text-gray-400"  xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                          <path stroke-linecap="round" stroke-linejoin="round" d="M9.568 3H5.25A2.25 2.25 0 003 5.25v4.318c0 .597.237 1.17.659 1.591l9.581 9.581c.699.699 1.78.872 2.607.33a18.095 18.095 0 005.223-5.223c.542-.827.369-1.908-.33-2.607L11.16 3.66A2.25 2.25 0 009.568 3z" />
                          <path stroke-linecap="round" stroke-linejoin="round" d="M6 6h.008v.008H6V6z" />
                        </svg>
                      </div>
                    <% end %>
                  </div>
                  <div class="min-w-0 flex-1 px-4 md:grid md:grid-cols-2 md:gap-4 flex items-center">
                    <div>
                      <p class="truncate text-sm font-medium text-indigo-600"><%= tag.friendly_name || tag.hostname_and_path %></p>
                      <% if tag.friendly_name %>
                        <p class="flex items-center text-sm text-gray-500">
                          <span class="truncate"><%= tag.hostname_and_path %></span>
                        </p>
                      <% end %>
                    </div>
                    <div class="text-end">
                      <div>
                        <% if tag.most_recent_tag_version %>
                          <p class="text-sm text-gray-900">
                            Last released <%= time_ago_in_words(tag.most_recent_tag_version.created_at) %> ago.
                          </p>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
                <div>
                  <svg class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
                  </svg>
                </div>
              </div>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  <% else %>
    <div class="space-y-6 col-span-3 border rounded-md">
      <div class="text-center mt-36 mb-36">
        <svg class="mx-auto h-12 w-12 text-gray-400"  xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M9.568 3H5.25A2.25 2.25 0 003 5.25v4.318c0 .597.237 1.17.659 1.591l9.581 9.581c.699.699 1.78.872 2.607.33a18.095 18.095 0 005.223-5.223c.542-.827.369-1.908-.33-2.607L11.16 3.66A2.25 2.25 0 009.568 3z" />
          <path stroke-linecap="round" stroke-linejoin="round" d="M6 6h.008v.008H6V6z" />
        </svg>

        <h3 class="mt-2 text-sm font-medium text-gray-900">You aren't hosting any tags yet.</h3>
        
        <div data-controller='modal'>
          <a data-action='modal#showModal dropdown#toggle' class='underline w-fit m-auto cursor-pointer text-gray-700 block px-4 py-2 text-sm hover:text-blue-500'>
            Install script snippet
          </a>
          <div class="relative z-10 opacity-0 hidden" data-modal-target='backdrop' aria-labelledby="modal-title" role="dialog" aria-modal="true">
            <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"></div>

            <div class="fixed inset-0 z-10 overflow-y-auto">
              <div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
                <div class="relative transform overflow-hidden rounded-lg bg-white px-4 pt-5 pb-4 text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-lg sm:p-6">
                  <div>
                    <div class="mt-3 text-center sm:mt-5">
                      <h3 class="text-base font-semibold leading-6 text-gray-900" id="modal-title">Paste the below HTML snippet into the top of the head of each page on your site.</h3>
                      <div class="mt-2">
                        <p class="text-sm text-gray-500 bg-gray-100 text-start whitespace-nowrap overflow-x-scroll p-2">
                          &lt;script&gt;!function(e){var t={},r=new XMLHttpRequest;r.open("GET","<%= current_organization.hosted_configuration_url %>",!1),r.send(),r.onload=function(){t=JSON.parse(r.responseText)};var o=Node.prototype.appendChild;Node.prototype.appendChild=function(){return arguments[0]=s(arguments[0]),o.apply(this,arguments)};var p=Node.prototype.insertBefore;Node.prototype.insertBefore=function(){return arguments[0]=s(arguments[0]),p.apply(this,arguments)};var n=Node.prototype.prepend;Node.prototype.prepend=function(){return arguments[0]=s(arguments[0]),n.apply(this,arguments)};var s=function(e){return"SCRIPT"===e.tagName&&t[e.src]&&(e.setAttribute("data-self-hosted","true"),e.setAttribute("src",t[e.src])),e}}();&lt;/script&gt;
                        </p>
                      </div>
                    </div>
                  </div>
                  <div class="mt-5 sm:mt-6 sm:grid sm:grid-flow-row-dense sm:grid-cols-2 sm:gap-3">
                    <div data-controller='copiable'>
                      <input type='hidden' data-copiable-target='textInput' value='&lt;script&gt;!function(e){var t={},r=new XMLHttpRequest;r.open("GET","<%= current_organization.hosted_configuration_url %>",!1),r.send(),r.onload=function(){t=JSON.parse(r.responseText)};var o=Node.prototype.appendChild;Node.prototype.appendChild=function(){return arguments[0]=s(arguments[0]),o.apply(this,arguments)};var p=Node.prototype.insertBefore;Node.prototype.insertBefore=function(){return arguments[0]=s(arguments[0]),p.apply(this,arguments)};var n=Node.prototype.prepend;Node.prototype.prepend=function(){return arguments[0]=s(arguments[0]),n.apply(this,arguments)};var s=function(e){return"SCRIPT"===e.tagName&&t[e.src]&&(e.setAttribute("data-self-hosted","true"),e.setAttribute("src",t[e.src])),e}}();&lt;/script&gt;'>
                      <button type="button" data-copiable-target='copyButton' data-action='copiable#copyText' class="w-full inline-flex items-center justify-center rounded-md border border-gray-200 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-200 focus:outline-none">
                        Copy
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4 ml-2">
                          <path stroke-linecap="round" stroke-linejoin="round" d="M15.666 3.888A2.25 2.25 0 0013.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 01-.75.75H9a.75.75 0 01-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 01-2.25 2.25H6.75A2.25 2.25 0 014.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 011.927-.184" />
                        </svg>
                      </button>
                    </div>
                    <button type="button" data-action='modal#hideModal' class="inline-flex items-center justify-center rounded-md border border-transparent bg-blue-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-blue-700 col-start-2">Got it</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <span class='block text-gray-700 text-sm'>Then</span>

        <%= link_to new_tag_path, class: 'mt-2 inline-flex items-center justify-center rounded-md border border-transparent bg-blue-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:ring-offset-gray-100' do %>
          Host your first tag
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/tags/new.html.erb
<%= render 'partials/page_header', page_title: 'Host a Tag', hide_new_tag_button: true %>

<div class='mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 mt-12'>
  <%= turbo_frame_tag "new_tag" do %>
    <%= render 'form', tag: current_organization.tags.new %>
  <% end %>
</div>

app/views/tags/show.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 mt-12">
  <div class="mx-auto max-w-3xl md:flex md:items-center md:justify-between md:space-x-5 lg:max-w-7xl ">
    <div class="flex items-center space-x-5 truncate">
      <div>
        <h1 class="text-2xl font-medium text-gray-900">Releases made by <%= @tag.hostname_and_path %></h1>
        <% if @tag.release_checks.any? %>
          <h2 class="text-sm font-small text-gray-600">As of <%= time_ago_in_words(@tag.most_recent_release_check.created_at) %> ago.</h2>
        <% end %>
      </div>
    </div>
    <div class="justify-stretch mt-6 flex flex-col-reverse space-y-4 space-y-reverse sm:flex-row-reverse sm:justify-end sm:space-y-0 sm:space-x-3 sm:space-x-reverse md:mt-0 md:flex-row md:space-x-3">
      <%= form_with url: tag_path, method: :delete do %>
        <button type='submit' class="rounded-md inline-flex justify-center items-center border border-red-300 bg-white px-4 py-2 text-sm font-medium text-red-700 shadow-sm hover:bg-red-200">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-1">
            <path stroke-linecap="round" stroke-linejoin="round" d="M9.75 9.75l4.5 4.5m0-4.5l-4.5 4.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          Stop hosting this tag
        </button>
      <% end %>
    </div>
  </div>
</div>

<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 mt-8">
  <% if @tag.tag_versions.any? %>
    <div class="overflow-hidden bg-white shadow sm:rounded-md">
      <ul role="list" class="divide-y divide-gray-200">
        <% @tag.tag_versions.most_recent_first.each do |tag_version| %>
          <li>
            <%= link_to tag_tag_version_path(@tag, tag_version), class: 'block hover:bg-gray-50' do %>
              <div class="flex items-center px-4 py-4 sm:px-6">
                <div class="flex min-w-0 flex-1 items-center">
                  <div class="min-w-0 flex-1 px-4 md:grid md:grid-cols-2 md:gap-4 flex items-center">
                    <div>
                      <p class="truncate text-sm font-medium text-gray-900 w-fit">
                        Version 
                        <span class="italic bg-gray-200 rounded p-1">
                          <%= tag_version.sha %>
                        </span>
                        <% if tag_version.is_currently_live? %>
                          <span class="ml-2 rounded bg-green-100 p-1 text-sm text-green-800">Currently live</span>
                        <% end %>
                      </p>
                      <p class="truncate italic text-sm font-medium text-gray-900">
                        <%= tag_version.minified_content_host_url || tag_version.original_content_host_url %>
                      </p>
                    </div>
                    <div class="text-end">
                      <div>
                        <p class="text-sm text-gray-900">
                          Released <%= time_ago_in_words(tag_version.created_at) %> ago.
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
                <div>
                  <svg class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
                  </svg>
                </div>
              </div>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  <% else %>
    <div class="space-y-6 col-span-3 border rounded-md">
      <div class="text-center mt-36 mb-36">
        <svg class="mx-auto h-12 w-12 text-gray-400"  xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M9.568 3H5.25A2.25 2.25 0 003 5.25v4.318c0 .597.237 1.17.659 1.591l9.581 9.581c.699.699 1.78.872 2.607.33a18.095 18.095 0 005.223-5.223c.542-.827.369-1.908-.33-2.607L11.16 3.66A2.25 2.25 0 009.568 3z" />
          <path stroke-linecap="round" stroke-linejoin="round" d="M6 6h.008v.008H6V6z" />
        </svg>

        <h3 class="mt-2 text-sm font-medium text-gray-900">This tag does not have any tag versions yet.</h3>
      </div>
    </div>
  <% end %>
</div>